//! Host-management commands: hosts, unpair, test, update-ip, export, import
//!
//! These commands operate on the connecto-managed entries in `~/.ssh/config`
//! through [`connecto_core::SshConfig`], which only ever touches blocks
//! preceded by the connecto marker — user-authored blocks are never listed,
//! rewritten, or removed. Each function takes the `SshConfig` to operate on,
//! so tests can point them at a temporary directory instead of `$HOME`.

use anyhow::Result;
use colored::Colorize;
use connecto_core::{paths, Config, HostEntry, SshConfig};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

use crate::SilentExit;

/// Wire format for `connecto export` / `connecto import`
///
/// The field names (including `HostEntry`'s `host`/`hostname`/`user`/
/// `identity_file`) are part of the on-disk schema; do not rename them.
#[derive(Serialize, Deserialize)]
struct ExportData {
    version: u32,
    hosts: Vec<HostEntry>,
    subnets: Vec<String>,
}

/// List paired hosts (from ~/.ssh/config)
pub fn run_hosts(ssh_config: &SshConfig) -> Result<()> {
    if !ssh_config.path().exists() {
        println!("{}", "No SSH config file found.".dimmed());
        return Ok(());
    }

    let hosts = ssh_config.list_hosts()?;

    if hosts.is_empty() {
        println!("{}", "No paired hosts found.".dimmed());
        println!();
        println!(
            "Pair with a device using: {}",
            "connecto scan && connecto pair 0".cyan()
        );
        return Ok(());
    }

    println!("{}", "Paired hosts:".bold());
    println!();
    for entry in &hosts {
        println!(
            "  {} {} → {}@{}",
            "•".green(),
            entry.host.cyan().bold(),
            entry.user.dimmed(),
            entry.hostname.dimmed()
        );
    }
    println!();
    println!("{}", "Connect with:".dimmed());
    println!("  {} ssh <hostname>", "→".cyan());
    println!();

    Ok(())
}

/// Remove a paired host from SSH config and delete its connecto-generated keys
///
/// Only connecto-managed blocks are removed. The identity key files are only
/// deleted when the file name follows the connecto naming convention
/// (`connecto_*` / `connecto_sync_*`) AND no other entry in the SSH config —
/// connecto-managed or user-authored — still references the same key (e.g. a
/// shared key reused across several pairings). Any other key (e.g. a
/// personal key configured via `--key` or `set-default-key`) is left
/// untouched.
pub fn run_unpair(ssh_config: &SshConfig, host: &str) -> Result<()> {
    if !ssh_config.path().exists() {
        println!("{} No SSH config file found.", "✗".red());
        return Err(SilentExit.into());
    }

    let entry = match ssh_config.remove_host(host)? {
        Some(entry) => entry,
        None => {
            println!("{} Host '{}' not found in SSH config.", "✗".red(), host);
            return Err(SilentExit.into());
        }
    };

    println!("{} Removed '{}' from SSH config.", "✓".green(), host.cyan());

    if entry.identity_file.is_empty() {
        return Ok(());
    }

    let key_path = paths::expand_tilde(&entry.identity_file)?;
    // The documented convention is `connecto_*` / `connecto_sync_*` — the
    // underscore matters, so a personal key merely named `connecto-...` is
    // never deleted.
    let is_connecto_key = key_path
        .file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| name.starts_with("connecto_"));

    if !is_connecto_key {
        println!(
            "{} Key left untouched (not generated by connecto): {}",
            "→".yellow(),
            key_path.display().to_string().dimmed()
        );
        return Ok(());
    }

    if key_still_referenced(ssh_config, &key_path) {
        println!(
            "{} Key left untouched (still referenced by other SSH config entries): {}",
            "→".yellow(),
            key_path.display().to_string().dimmed()
        );
        return Ok(());
    }

    let pub_path = key_path.with_extension("pub");
    if key_path.exists() {
        fs::remove_file(&key_path)?;
        println!(
            "{} Deleted private key: {}",
            "✓".green(),
            key_path.display().to_string().dimmed()
        );
    }
    if pub_path.exists() {
        fs::remove_file(&pub_path)?;
        println!(
            "{} Deleted public key: {}",
            "✓".green(),
            pub_path.display().to_string().dimmed()
        );
    }

    Ok(())
}

/// Whether any remaining SSH config entry still references `key_path`
///
/// Checks the remaining connecto-managed entries AND scans the raw config
/// text for `IdentityFile` lines (so user-authored blocks count too). A key
/// shared by several pairings — e.g. a `default_key` named `connecto_*` —
/// must survive unpairing one of them. Errors reading the config are treated
/// as "still referenced" so we never delete a key we cannot prove is unused.
fn key_still_referenced(ssh_config: &SshConfig, key_path: &Path) -> bool {
    match ssh_config.list_hosts() {
        Ok(hosts) => {
            let referenced = hosts
                .iter()
                .filter(|h| !h.identity_file.is_empty())
                .any(|h| paths::expand_tilde(&h.identity_file).is_ok_and(|p| p == key_path));
            if referenced {
                return true;
            }
        }
        Err(_) => return true,
    }

    match fs::read_to_string(ssh_config.path()) {
        Ok(content) => content.lines().any(|line| {
            identity_file_value(line)
                .and_then(|value| paths::expand_tilde(value).ok())
                .is_some_and(|p| p == key_path)
        }),
        Err(_) => true,
    }
}

/// Extract the value of an `IdentityFile` config line, if it is one
///
/// Matches the keyword case-insensitively with whitespace or `=` after it
/// (like ssh itself) and strips surrounding double quotes from the value.
fn identity_file_value(line: &str) -> Option<&str> {
    const KEYWORD: &str = "IdentityFile";
    let trimmed = line.trim();
    if trimmed.len() <= KEYWORD.len() || !trimmed.is_char_boundary(KEYWORD.len()) {
        return None;
    }
    let (head, rest) = trimmed.split_at(KEYWORD.len());
    if !head.eq_ignore_ascii_case(KEYWORD)
        || !rest.starts_with(|c: char| c.is_whitespace() || c == '=')
    {
        return None;
    }
    let value = rest
        .trim_start_matches(|c: char| c.is_whitespace() || c == '=')
        .trim_end();
    let value = value
        .strip_prefix('"')
        .and_then(|v| v.strip_suffix('"'))
        .unwrap_or(value);
    (!value.is_empty()).then_some(value)
}

/// Test SSH connection to a paired host
pub fn run_test(host: &str) -> Result<()> {
    use std::process::Command;

    println!(
        "{} Testing connection to {}...",
        "→".cyan(),
        host.cyan().bold()
    );

    let output = Command::new("ssh")
        .args([
            "-o",
            "ConnectTimeout=5",
            "-o",
            "BatchMode=yes",
            host,
            "echo",
            "connecto-ok",
        ])
        .output();

    match output {
        Ok(result) => {
            if result.status.success() {
                let stdout = String::from_utf8_lossy(&result.stdout);
                if stdout.trim() == "connecto-ok" {
                    println!("{} Connection successful!", "✓".green());
                } else {
                    println!(
                        "{} Connection established but unexpected response.",
                        "⚠".yellow()
                    );
                }
                Ok(())
            } else {
                let stderr = String::from_utf8_lossy(&result.stderr);
                println!("{} Connection failed.", "✗".red());
                if !stderr.is_empty() {
                    println!("{}", stderr.dimmed());
                }
                println!();
                println!("{}", "Troubleshooting:".bold());
                println!("  {} Check if the host is online", "•".dimmed());
                println!(
                    "  {} Verify the IP is correct: {}",
                    "•".dimmed(),
                    "connecto hosts".cyan()
                );
                println!(
                    "  {} Update IP if changed: {}",
                    "•".dimmed(),
                    format!("connecto update-ip {} <new-ip>", host).cyan()
                );
                Err(SilentExit.into())
            }
        }
        Err(e) => {
            println!("{} Failed to run ssh: {}", "✗".red(), e);
            Err(SilentExit.into())
        }
    }
}

/// Update IP address for a paired host
pub fn run_update_ip(ssh_config: &SshConfig, host: &str, new_ip: &str) -> Result<()> {
    if !ssh_config.path().exists() {
        println!("{} No SSH config file found.", "✗".red());
        return Err(SilentExit.into());
    }

    match ssh_config.update_hostname(host, new_ip)? {
        Some(old_ip) => {
            println!(
                "{} Updated '{}' IP: {} → {}",
                "✓".green(),
                host.cyan(),
                old_ip.dimmed(),
                new_ip.cyan().bold()
            );
            Ok(())
        }
        None => {
            println!("{} Host '{}' not found in SSH config.", "✗".red(), host);
            Err(SilentExit.into())
        }
    }
}

/// Export paired hosts configuration
pub fn run_export(ssh_config: &SshConfig, output: Option<&str>) -> Result<()> {
    let cfg = Config::load().unwrap_or_default();

    let export_data = ExportData {
        version: 1,
        hosts: ssh_config.list_hosts()?,
        subnets: cfg.subnets,
    };

    let json = serde_json::to_string_pretty(&export_data)?;

    if let Some(path) = output {
        fs::write(path, &json)?;
        println!(
            "{} Exported {} host(s) to {}",
            "✓".green(),
            export_data.hosts.len(),
            path.cyan()
        );
    } else {
        println!("{}", json);
    }

    Ok(())
}

/// Import paired hosts configuration
pub fn run_import(ssh_config: &SshConfig, file: &str) -> Result<()> {
    let content = fs::read_to_string(file)?;
    let data: ExportData = serde_json::from_str(&content)?;

    if data.version != 1 {
        return Err(anyhow::anyhow!(
            "Unsupported export version: {}",
            data.version
        ));
    }

    // Only add hosts that are not already managed, by exact alias match (the
    // old substring check silently skipped imports on prefix collisions).
    let existing: std::collections::HashSet<String> = ssh_config
        .list_hosts()?
        .into_iter()
        .map(|h| h.host)
        .collect();

    let mut added = 0;
    for host in &data.hosts {
        if existing.contains(&host.host) {
            continue;
        }
        ssh_config.add_host(host)?;
        added += 1;
    }

    if added > 0 {
        println!("{} Imported {} host(s) to SSH config.", "✓".green(), added);
    } else {
        println!("{} All hosts already exist in SSH config.", "→".yellow());
    }

    // Import subnets
    let mut cfg = Config::load().unwrap_or_default();
    let mut subnet_added = 0;
    for subnet in &data.subnets {
        if cfg.add_subnet(subnet) {
            subnet_added += 1;
        }
    }

    if subnet_added > 0 {
        cfg.save()?;
        println!(
            "{} Imported {} subnet(s) to config.",
            "✓".green(),
            subnet_added
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::SilentExit;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn ssh_config_in(temp: &TempDir) -> SshConfig {
        SshConfig::new(temp.path().join(".ssh").join("config"))
    }

    /// Create a fake private/public key pair on disk and return the private path
    fn fake_key(dir: &Path, name: &str) -> PathBuf {
        fs::create_dir_all(dir).unwrap();
        let key = dir.join(name);
        fs::write(&key, "private").unwrap();
        fs::write(dir.join(format!("{}.pub", name)), "public").unwrap();
        key
    }

    fn entry(host: &str, identity_file: &str) -> HostEntry {
        HostEntry {
            host: host.to_string(),
            hostname: "192.168.1.20".to_string(),
            user: "alice".to_string(),
            identity_file: identity_file.to_string(),
        }
    }

    fn assert_silent_exit(err: &anyhow::Error) {
        assert!(
            err.downcast_ref::<SilentExit>().is_some(),
            "expected SilentExit, got: {err:#}"
        );
    }

    #[test]
    fn test_unpair_round_trip_deletes_connecto_keys() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        let key = fake_key(&temp.path().join(".ssh"), "connecto_my-device");
        let pub_key = key.with_extension("pub");

        ssh_config
            .add_host(&entry("my-device", &key.display().to_string()))
            .unwrap();

        run_unpair(&ssh_config, "my-device").unwrap();

        assert!(ssh_config.list_hosts().unwrap().is_empty());
        assert!(
            !key.exists(),
            "connecto-generated private key must be deleted"
        );
        assert!(
            !pub_key.exists(),
            "connecto-generated public key must be deleted"
        );
    }

    #[test]
    fn test_unpair_deletes_sync_named_keys() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        let key = fake_key(&temp.path().join(".ssh"), "connecto_sync_peer");

        ssh_config
            .add_host(&entry("peer", &key.display().to_string()))
            .unwrap();

        run_unpair(&ssh_config, "peer").unwrap();
        assert!(!key.exists());
    }

    #[test]
    fn test_unpair_leaves_foreign_named_key_untouched() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        // A key that does not follow the connecto naming convention (e.g. the
        // user's primary key configured via --key / set-default-key).
        let key = fake_key(&temp.path().join(".ssh"), "id_ed25519");
        let pub_key = key.with_extension("pub");

        ssh_config
            .add_host(&entry("shared-key-host", &key.display().to_string()))
            .unwrap();

        run_unpair(&ssh_config, "shared-key-host").unwrap();

        assert!(ssh_config.list_hosts().unwrap().is_empty());
        assert!(
            key.exists(),
            "non-connecto private key must never be deleted"
        );
        assert!(
            pub_key.exists(),
            "non-connecto public key must never be deleted"
        );
    }

    /// Finding [7]: a connecto-named key shared by several pairings must
    /// survive unpairing one of them, and only be deleted with the last one.
    #[test]
    fn test_unpair_keeps_key_shared_with_other_paired_host() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        // A reused default key that happens to follow the connecto convention.
        let key = fake_key(&temp.path().join(".ssh"), "connecto_main");
        let pub_key = key.with_extension("pub");
        let key_str = key.display().to_string();

        ssh_config.add_host(&entry("laptop", &key_str)).unwrap();
        ssh_config.add_host(&entry("desktop", &key_str)).unwrap();

        // Unpairing one host must NOT delete the still-shared key.
        run_unpair(&ssh_config, "laptop").unwrap();
        assert!(key.exists(), "shared private key must not be deleted");
        assert!(pub_key.exists(), "shared public key must not be deleted");
        assert_eq!(ssh_config.list_hosts().unwrap().len(), 1);

        // Unpairing the last host referencing it deletes the key.
        run_unpair(&ssh_config, "desktop").unwrap();
        assert!(!key.exists());
        assert!(!pub_key.exists());
    }

    /// Finding [7]: a user-authored (markerless) block referencing the same
    /// key also blocks deletion — the raw config text is scanned too.
    #[test]
    fn test_unpair_keeps_key_referenced_by_user_authored_block() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        let key = fake_key(&temp.path().join(".ssh"), "connecto_reused");
        let key_str = key.display().to_string();

        // Hand-written block (no connecto marker) using the same key, with
        // ssh-style lowercase keyword and quoting.
        fs::write(
            ssh_config.path(),
            format!("Host byhand\n    HostName example.com\n    identityfile \"{key_str}\"\n"),
        )
        .unwrap();
        ssh_config.add_host(&entry("managed", &key_str)).unwrap();

        run_unpair(&ssh_config, "managed").unwrap();

        assert!(
            key.exists(),
            "key referenced by a user-authored block must not be deleted"
        );
        let content = fs::read_to_string(ssh_config.path()).unwrap();
        assert!(content.contains("Host byhand"));
    }

    /// Finding [35]: only the documented `connecto_*` convention (with
    /// underscore) marks a key as connecto-generated; `connecto-personal`
    /// and the like are user keys and must never be deleted.
    #[test]
    fn test_unpair_leaves_connecto_personal_named_key_untouched() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        let key = fake_key(&temp.path().join(".ssh"), "connecto-personal");
        let pub_key = key.with_extension("pub");

        ssh_config
            .add_host(&entry("mybox", &key.display().to_string()))
            .unwrap();

        run_unpair(&ssh_config, "mybox").unwrap();

        assert!(ssh_config.list_hosts().unwrap().is_empty());
        assert!(
            key.exists(),
            "key without the connecto_ underscore convention must not be deleted"
        );
        assert!(pub_key.exists());
    }

    #[test]
    fn test_unpair_never_touches_user_authored_blocks() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        let key = fake_key(&temp.path().join(".ssh"), "id_rsa");

        // A hand-written block without the connecto marker.
        let foreign = format!(
            "Host myserver\n    HostName example.com\n    User carol\n    IdentityFile {}\n",
            key.display()
        );
        fs::write(ssh_config.path(), &foreign).unwrap();

        let err = run_unpair(&ssh_config, "myserver").unwrap_err();
        assert_silent_exit(&err);

        // Config and keys are untouched.
        assert_eq!(fs::read_to_string(ssh_config.path()).unwrap(), foreign);
        assert!(key.exists());
    }

    #[test]
    fn test_unpair_unknown_host_exits_nonzero() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        ssh_config.add_host(&entry("known", "/k/known")).unwrap();

        let err = run_unpair(&ssh_config, "unknown").unwrap_err();
        assert_silent_exit(&err);
        assert_eq!(ssh_config.list_hosts().unwrap().len(), 1);
    }

    #[test]
    fn test_unpair_missing_config_exits_nonzero() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);

        let err = run_unpair(&ssh_config, "anything").unwrap_err();
        assert_silent_exit(&err);
    }

    #[test]
    fn test_update_ip_round_trip() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        ssh_config.add_host(&entry("box", "/k/box")).unwrap();

        run_update_ip(&ssh_config, "box", "10.9.8.7").unwrap();

        let hosts = ssh_config.list_hosts().unwrap();
        assert_eq!(hosts[0].hostname, "10.9.8.7");
        // The rest of the entry is intact.
        assert_eq!(hosts[0].user, "alice");
        assert_eq!(hosts[0].identity_file, "/k/box");
    }

    #[test]
    fn test_update_ip_does_not_touch_user_authored_block() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        fs::create_dir_all(ssh_config.path().parent().unwrap()).unwrap();

        let foreign = "Host prod\n    HostName 1.1.1.1\n    User root\n";
        fs::write(ssh_config.path(), foreign).unwrap();

        let err = run_update_ip(&ssh_config, "prod", "2.2.2.2").unwrap_err();
        assert_silent_exit(&err);
        assert_eq!(fs::read_to_string(ssh_config.path()).unwrap(), foreign);
    }

    #[test]
    fn test_update_ip_unknown_host_exits_nonzero() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);
        ssh_config.add_host(&entry("known", "/k/known")).unwrap();

        let err = run_update_ip(&ssh_config, "unknown", "10.0.0.1").unwrap_err();
        assert_silent_exit(&err);
    }

    #[test]
    fn test_export_import_round_trip() {
        let temp = TempDir::new().unwrap();
        let source = ssh_config_in(&temp);
        source.add_host(&entry("alpha", "/k/alpha")).unwrap();
        source.add_host(&entry("beta", "/k/beta")).unwrap();

        let export_path = temp.path().join("export.json");
        run_export(&source, Some(&export_path.display().to_string())).unwrap();

        // Import into a fresh config.
        let dest = SshConfig::new(temp.path().join("dest").join("config"));
        run_import(&dest, &export_path.display().to_string()).unwrap();

        let hosts = dest.list_hosts().unwrap();
        assert_eq!(hosts.len(), 2);
        assert_eq!(hosts[0], entry("alpha", "/k/alpha"));
        assert_eq!(hosts[1], entry("beta", "/k/beta"));

        // Importing again must not duplicate entries.
        run_import(&dest, &export_path.display().to_string()).unwrap();
        assert_eq!(dest.list_hosts().unwrap().len(), 2);
    }

    #[test]
    fn test_import_rejects_unknown_version() {
        let temp = TempDir::new().unwrap();
        let ssh_config = ssh_config_in(&temp);

        let bad = temp.path().join("bad.json");
        fs::write(&bad, r#"{"version":2,"hosts":[],"subnets":[]}"#).unwrap();

        let err = run_import(&ssh_config, &bad.display().to_string()).unwrap_err();
        assert!(err.to_string().contains("Unsupported export version"));
    }
}
